version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.26
    restart: always
    ports:
    - "4477:4477"
    environment:
      PRISMA_CONFIG: |
        port: 4477
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-46-137-170-51.eu-west-1.compute.amazonaws.com
            database: de3rgd9e0ll82r
            ssl: true
            user: qzbkllqqqnpsir
            password: 3b209ace1b5c1a82771eaaedaf3299d7bd4970b10ebc5ad4034bdb6fddf08c0b
            rawAccess: true
            port: '5432'
            migrations: true