version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.27.3
    restart: always
    ports:
    - "4444:4444"
    environment:
      PRISMA_CONFIG: |
        port: 4444
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-228-224-37.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: dbj49i3h9hk6su
            ssl: true
            user: wkyuyfpkwosdyz
            password: b48e545852343685fbc4253f2abd5313c2bd0bbbef97047d5917458c74dbac2b
            migrations: true